client_id = "7c23ec0e48187aef7a215451536fc8f3"
name = "convertflow-ai"
application_url = "https://olivedrab-mosquito-163393.hostingersite.com"
embedded = true
distribution = "custom"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_themes,write_themes,read_products,write_products,read_content,write_content"

[auth]
redirect_urls = [
  "https://olivedrab-mosquito-163393.hostingersite.com/auth/callback",
  "https://olivedrab-mosquito-163393.hostingersite.com/auth/shopify/callback",
  "https://olivedrab-mosquito-163393.hostingersite.com/api/auth/callback"
]
